"""
Agent 2: Question Generator
Generates situational, technical, and behavioral interview questions
specifically derived from the candidate's uploaded resume profile.
"""

import os
import json
import random
import traceback
from typing import Dict, List, Tuple

class QuestionGenerator:
    """Generates contextual, resume-based interview questions for candidates"""

    # Time limits by difficulty/experience level
    TIME_LIMITS = {
        "easy": 45,       # 45 seconds
        "medium": 60,     # 60 seconds
        "hard": 90,       # 90 seconds
        "very_hard": 120, # 120 seconds
    }

    @staticmethod
    def get_difficulty(years_experience: int) -> str:
        """Determine difficulty level based on years of experience"""
        if years_experience >= 10:
            return "very_hard"
        elif years_experience >= 5:
            return "hard"
        elif years_experience >= 2:
            return "medium"
        else:
            return "easy"

    @staticmethod
    def _generate_with_gemini(profile: Dict, previous_questions: List[str] = None) -> Tuple[str, int, str]:
        """Generate a contextual interview question directly from the resume using Gemini AI"""
        import google.generativeai as genai

        api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        if not api_key:
            raise ValueError("No Gemini API key available")

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")

        role = profile.get("role", "Software Professional")
        years = profile.get("years_experience", 2)
        seniority = profile.get("seniority_level", "Mid-Level")
        industry = profile.get("industry", "Tech")
        skills = profile.get("skills", [])
        companies = profile.get("companies", [])
        projects = profile.get("projects", [])
        summary = profile.get("resume_summary", "")
        raw_text = profile.get("raw_text", "")

        prev_q_str = ""
        if previous_questions:
            prev_q_str = "PREVIOUSLY ASKED QUESTIONS (DO NOT REPEAT OR DUPLICATE SIMILAR TOPICS):\n" + "\n".join(f"- {q}" for q in previous_questions)

        prompt = f"""
You are an expert technical interviewer at a top technology company.
Your goal is to conduct a personalized interview based on the candidate's uploaded resume.

CANDIDATE PROFILE FROM RESUME:
- Primary Role: {role}
- Seniority: {seniority} ({years} years experience)
- Industry: {industry}
- Key Skills: {', '.join(skills) if skills else 'Not specified'}
- Past Companies: {', '.join(companies) if companies else 'Not specified'}
- Key Projects: {'; '.join(projects) if projects else 'Not specified'}
- Resume Summary: {summary}
- Resume Snippet: {raw_text[:1500]}

{prev_q_str}

TASK:
Generate EXACTLY 1 challenging, highly specific, and realistic interview question that DIRECTLY references details from the candidate's resume (their specific tools, past projects, company experience, or technical accomplishments).
The question should test their real-world problem-solving abilities, system design, architectural choices, or leadership in their target role.

Return ONLY a JSON object with EXACTLY the following structure (no markdown wrapping, no extra text):
{{
  "question": "In your resume, you mentioned leading X using Y at Z. If you faced...",
  "question_type": "resume_based",
  "recommended_time_seconds": 60,
  "context_tag": "Specific focus area or skill being tested"
}}
"""
        response = model.generate_content(prompt)
        response_text = response.text.strip()

        if response_text.startswith("```"):
            lines = response_text.splitlines()
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            response_text = "\n".join(lines).strip()

        data = json.loads(response_text)
        question = data.get("question", "").strip()
        q_type = data.get("question_type", "resume_based")
        time_limit = int(data.get("recommended_time_seconds") or QuestionGenerator.TIME_LIMITS.get(QuestionGenerator.get_difficulty(years), 60))

        if not question:
            raise ValueError("Empty question generated by Gemini")

        return question, time_limit, q_type

    @staticmethod
    def _generate_fallback(profile: Dict, previous_questions: List[str] = None) -> Tuple[str, int, str]:
        """Fallback rule-based question generator using candidate's parsed resume metadata"""
        role = profile.get("role", "Software Professional")
        years = profile.get("years_experience", 2)
        skills = profile.get("skills", ["software development", "problem solving"])
        companies = profile.get("companies", [])
        projects = profile.get("projects", [])
        industry = profile.get("industry", "General Tech")

        difficulty = QuestionGenerator.get_difficulty(years)
        time_limit = QuestionGenerator.TIME_LIMITS[difficulty]

        skill1 = skills[0] if len(skills) > 0 else "software engineering"
        skill2 = skills[1] if len(skills) > 1 else "cloud infrastructure"
        comp_name = companies[0] if companies else "your previous role"
        project_desc = projects[0] if projects else f"a critical system using {skill1}"

        templates = [
            f"Based on your resume experience as a {role} working with {skill1} at {comp_name}, walk me through a time when a critical bug occurred in production. How did you diagnose and resolve it?",
            f"You listed {skill1} and {skill2} as key competencies on your resume. How would you design a scalable architecture combining these technologies for a high-traffic {industry} platform?",
            f"In your resume, you highlighted your background with {project_desc}. What were the biggest technical tradeoffs you had to make, and what would you do differently today?",
            f"As a {role} with {years} years of experience in {industry}, how do you handle conflicting priorities between short-term feature delivery and long-term tech debt reduction?",
            f"Reflecting on your work at {comp_name}, describe a situation where a technical project hit an unexpected bottleneck. What specific actions did you take to unblock the team?",
        ]

        # Filter out questions already used if possible
        available = [t for t in templates if not previous_questions or t not in previous_questions]
        question = random.choice(available) if available else random.choice(templates)

        return question, time_limit, "resume_based"

    @staticmethod
    def generate_question(profile: Dict, previous_questions: List[str] = None) -> Tuple[str, int, str]:
        """
        Generate a contextual interview question based on candidate profile.
        Attempts Gemini AI first; falls back to template generator if offline/error.
        
        Returns:
            (question_text, time_limit_seconds, question_type)
        """
        if not profile:
            profile = {}

        try:
            return QuestionGenerator._generate_with_gemini(profile, previous_questions)
        except Exception as e:
            print(f"[QuestionGenerator] Gemini generation failed/skipped: {e}. Falling back to templates.")
            return QuestionGenerator._generate_fallback(profile, previous_questions)

    @staticmethod
    def generate_question_batch(profile: Dict, count: int = 5) -> List[Dict]:
        """Generate multiple distinct resume-based questions for a candidate session"""
        questions = []
        previous = []
        for _ in range(count):
            q_text, time_limit, q_type = QuestionGenerator.generate_question(profile, previous_questions=previous)
            previous.append(q_text)
            questions.append({
                "question": q_text,
                "time_limit": time_limit,
                "type": q_type,
            })
        return questions
